language: node_js
node_js:
- '6'
script: NODE_ENV=test mocha test/index_tests
deploy:
  provider: heroku
  api_key:
    secure: WUl+WeuUslmowwQk2oM2P3LVCcIm7ZaReYRRK29Uc2qs5i0x36y5Q5NFl436OMHbXcr8ptNhY596WeSvucUZ1ro9tgIKa1BzEvfVMRXjY4asTyzKGreB1BNPRVG4yZiOmwW6ePRS2M0UKmnMvxC28h9O7BuVflIS7+7cRlSIktjyOrfplDRM6eObxE2taFDCBMKWNhpYkfyiwEmneGo24RY3DDBlVWAtgeGksvt4Iaw4lflOHquTpvN6NTerRs6uREuFuGjoWKHNkOFqjq0M0yVe59JUTus63r3+9F1Db4FPT8kd6VKgwnDykOpMRmzKSy0+np/oHFqbuInY2UTwyxToaoH86xJw37TIHhYUNKSafrJpUvKCtGAsvYxWDRwhZC+aXDxxMiRtBRuMCjCV1ZddXs9CunZZ2Ag0SKG//nFySZJWkV7Y54AKqXvKstj+nB/5IgoYcIMGAco5f07qV9yKROYt54JMimD3DfhzmUyrFo0nb4JSMuf6qAfFzXkVTu2gX7xtGunGPxCSc24NNtEXyhMmZsRYLWYUb6FG7lXp10K8eo8zrZO+nJX68Rlt6IpGhToDbO1QdD3xK/wnloUblbftP5nFJDGiTJNrypmaAWoWcGvgHuTiD7gANNyLaW/MRP6az8Ht4XprHstg0fmxp7pblDZFxUwO+xShqs0=
